spring.datasource.url=jdbc:mysql://mysql-d1f2300-masaboolivier21-285e.c.aivencloud.com:23167/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_xnejbnpMth2CDAV7XCK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=23167
